// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrixidfeuqyrjcwigllb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxyaXhpZGZldXF5cmpjd2lnbGxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUwNTYwOTQsImV4cCI6MjA1MDYzMjA5NH0.Xli622wSVTUdxPelEaIT9_GkGTrAm8eARtBreBICBjc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);